apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ideas-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "ideas-frontend-ip"
  labels:
    app: angularpage
#spec:
#  backend:
#    serviceName: ideas-backend
#    servicePort: 80
spec:
    rules:
    - http:
        paths:
        - path: /
          backend:
              serviceName: ideas-angular
              servicePort: 80
        - path: /api
          backend:
              serviceName: ideas-express
              servicePort: 3000 
---
apiVersion: v1
kind: Service
metadata:
  name: ideas-angular
  labels:
    app: angularpage
spec:
  type: NodePort
  selector:
    app: angularpage
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
    name: ideas-express
    labels:
        app: details
spec:
    type: NodePort
    selector:
        app: details
    ports:
    - port: 3000
      targetPort: 3000