apiVersion: skaffold/v2alpha1
kind: Config
metadata:
  name: ideas-gke-dev
build:
  artifacts:
  - image: gcr.io/third-pulsar-248314/ideas-angular
    context: angular
  - image: gcr.io/third-pulsar-248314/ideas-express
    context: express
  - image: gcr.io/third-pulsar-248314/ideas-mongodb
    context: mongo
deploy:
  kubectl:
    manifests:
    - ideas.yaml
    - ideas-ingress.yaml
